services:
  cashier-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: litecashier_cashier_api
    restart: always
    ports:
      - "127.0.0.1:6768:6768"
    volumes:
      - ./POS/wwwroot/Images:/app/wwwroot/Images
      - ./POS/wwwroot/app:/app/wwwroot/app
      - ./POS/appsettings.Cloud.json:/app/appsettings.Production.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:6768
